name: Publish Dockerfile image

on:
  push:
    branches:
      - "master"
      - "dev"
  pull_request:
    branches:
      - "master"

jobs:
  push_to_registry:
    name: Push Dockerfile image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Build docker-image
        run: docker build . --tag alessiow01/frontend:latest
      - name: log in to github
        run: docker login ghcr.io -u ${{ secrets.SECRET_GITHUB_USERNAME }} -p ${{ secrets.SECRET_GITHUB_PASSWORD }}
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: push
        run: docker push alessiow01/frontend:latest   
      - name: webhook
        run: curl -X POST ${{ secrets.WEBHOOK_URL }}
